server:
  port: 8112
  context-path: /eureka_service

spring:
  application:
    name: eureka-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}:${random.value} #实例id
    # hostname: 47.93.204.1
    ip-address: 47.93.204.1 # 阿里云上部署使用
    prefer-ip-address: true # 显示ip地址
    status-page-url-path: ${server.context-path}/info
    health-check-url-path: ${server.context-path}/health

management:
  security:
    enabled: false # 关闭用户验证
