# 服务器端口
server:
  port: 8008
  context-path: /web

# 数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/test?characterEncoding=utf-8&useSSL=false
    username: root
    password: hcp1101@!#
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  devtools:
    restart:
      enabled: false


