# 服务端口
server:
  port: 8009
  context-path: /config_server

spring:
  application:
      name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HuAngchping/config-repo.git
          username: chap@gmail.com
          password: 1101
          search-paths: configclient #myconfig/dev,myconfig/test,myconfig/prod 搜索 git地址https://github.com/HuAngchping/+myconfig/dev
        #native:
          #search-locations: 加载本地配置 /User/huang/Documents/里的配置文件
          #其它配置中心 百度disconf Spring Cloud Consul

# 简单用户验证
security:
  user:
    name: config
    password: config
#logging:
#  config: http://127.0.0.1:8009/config_server/configserver/default/master/logback-spring.xml
# 数据库连接配置

  #profiles:
    #active: 检测src/main/resources 下的配置


#http://127.0.0.1:8009/config_server/{application}/{profile}/{label} 例子http://127.0.0.1:8009/config_server/config-client/dev/master 或http://127.0.0.1:8009/config_server/config-client/dev
